apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cilium-test-hostnetwork
  namespace: cilium-test
subjects:
- kind: ServiceAccount
  name: default
  namespace: cilium-test
roleRef:
- kind: Role
  name: cilium-test-hostnetwork
  apiGroup: rbac.authorization.k8s.io
